### ISSUE TITLE
Funktion verbessern

### ISSUE THREAD

**Issue by MatusGasparik** [FabianRuefenacht/UebungenHS2022#1]
https://github.com/FabianRuefenacht/UebungenHS2022/blob/b62cbdd7069e03f85dc0bdb85101e59bd13dc4fe/Uebung02/Uebung02.2.js#L2-L6

Könnte man sich das `zahl + 1` noch sparen? Wie würde eine 1-zeilige Version der Funktion aussehen?

**Comment by FabianRuefenacht** [comment]
Danke @MatusGasparik für die Anmerkungen.
Ja, zahl + 1 konnte durch Math.ceil() ersetzt werden.
Die einzeilige Funktion konnte ebenfalls erstellt werden.
